/**
 * Copyrigt (2020, ) Institute of Software, Chinese Academy of Sciences
 */
package com.cn.services;

import org.springframework.beans.factory.annotation.Autowired;
import com.cn.mappers.Pm_bugMapper;
import com.cn.models.Pm_bug;
import com.github.tools.annotations.api.FunctionDescriber;
import com.github.webfrk.core.HttpBodyHandler;
import com.github.tools.annotations.ServiceDefinition;
import java.math.BigInteger;
import javax.validation.constraints.*;
import com.github.tools.annotations.api.Required;
import javax.validation.*;

/**
 * This code is auto-generated by <code>ServiceGenerator<code>
 *
 */
@ServiceDefinition
public class Pm_bugService extends HttpBodyHandler {

	@Autowired
	private Pm_bugMapper pm_bugMapper;

	@FunctionDescriber(shortName = "根据项目id展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getPm_bug(@Required(true) BigInteger project_id) {
		return pm_bugMapper.getPm_bug(project_id);
	}

	@FunctionDescriber(shortName = "添加缺陷信息", description = "暂无", prerequisite = "暂无")
	public void addBugInfo(@Valid Pm_bug pm_bug) {
		 pm_bugMapper.addBugInfo(pm_bug);
	}

	@FunctionDescriber(shortName = "根据领取人展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getBugByUser(@Required(true) BigInteger project_id) {
		return pm_bugMapper.getBugByUser(project_id);
	}

	@FunctionDescriber(shortName = "根据领取人和状态展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getBugByStatea(@Required(true) BigInteger project_id,@Required(true) String bug_user) {
		return pm_bugMapper.getBugByStatea(project_id, bug_user);
	}

	@FunctionDescriber(shortName = "根据领取人和状态展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getBugByStateb(@Required(true) BigInteger project_id,@Required(true) String bug_user) {
		return pm_bugMapper.getBugByStateb(project_id, bug_user);
	}

	@FunctionDescriber(shortName = "根据领取人和状态展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getBugByStatec(@Required(true) BigInteger project_id,@Required(true) String bug_user) {
		return pm_bugMapper.getBugByStatec(project_id, bug_user);
	}

	@FunctionDescriber(shortName = "根据领取人和状态展示该项目的所有缺陷", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_bug> getBugByStated(@Required(true) BigInteger project_id,@Required(true) String bug_user) {
		return pm_bugMapper.getBugByStated(project_id, bug_user);
	}


	@FunctionDescriber(shortName = "根据缺陷id查询缺陷信息", description = "暂无", prerequisite = "暂无")
	public com.cn.models.Pm_bug queryBugById(BigInteger bug_id) {
		return pm_bugMapper.queryBugById(bug_id);
	}

	@FunctionDescriber(shortName = "更新项目信息", description = "暂无", prerequisite = "暂无")
	public java.lang.Integer updateBug(
			@Valid String bug_id, String bug_name, String bug_test, String bug_rem, String bug_state,String bug_pri,String bug_ptime,String bug_user,Integer project_id,String bug_spr
	) {
		Pm_bug bug = new Pm_bug();
		bug.setBug_id(Integer.parseInt(bug_id));
		bug.setBug_name(bug_name);
		bug.setBug_pri(bug_pri);
		bug.setBug_ptime(bug_ptime);
		bug.setBug_rem(bug_rem);
		bug.setBug_spr(bug_spr);
		bug.setBug_state(bug_state);
		bug.setBug_test(bug_test);
		bug.setBug_user(bug_user);
		bug.setProject_id(project_id);
		return pm_bugMapper.updateBug(bug);
	}
}
