package com.cn.services;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import com.github.tools.annotations.api.FunctionDescriber;
import com.github.webfrk.core.HttpBodyHandler;
import com.github.tools.annotations.ServiceDefinition;
import com.github.tools.annotations.api.Required;
import com.cn.mappers.Pm_projectMapper;
import com.cn.models.Pm_project;


/**
 * This code is auto-generated by <code>ServiceGenerator<code>
 *
 */
@ServiceDefinition
public class Pm_projectService extends HttpBodyHandler {

	@Autowired
	private Pm_projectMapper pm_projectMapper;

	/*
	 * @FunctionDescriber(shortName = "查询用户进入项目得权限", description = "暂无",
	 * prerequisite = "暂无") public java.util.List<com.cn.models.Pm_project>
	 * getPm_project() { return pm_projectMapper.getPm_project(); }
	 */

	@FunctionDescriber(shortName = "归档项目/取消归档项目", description = "暂无", prerequisite = "暂无")
	public void updatePm_project(Integer project_id, @Required(false) Integer project_state) {
		 pm_projectMapper.updatePm_project(project_id, project_state);
	}
	
	@FunctionDescriber(shortName = "更新项目信息", description = "暂无", prerequisite = "暂无")
	public java.lang.Integer updateProject(@Valid Pm_project pm_project) {
		return pm_projectMapper.updateProject(pm_project);
	}

	@FunctionDescriber(shortName = "添加项目信息", description = "暂无", prerequisite = "暂无")
	public void addProjectInfo(@Valid Pm_project pm_project) {
		 pm_projectMapper.addProjectInfo(pm_project);
	}

	//根据项目id查询项目信息
		@FunctionDescriber(shortName = "根据项目id查询项目信息", description = "暂无", prerequisite = "暂无")
		public Pm_project queryById(Integer project_id) throws Exception {
			if(project_id == null){
				throw new Exception("请求参数有问题");
			}
			Pm_project pm_project = pm_projectMapper.queryById(project_id);
			return pm_project;
		}
		
	/*@FunctionDescriber(shortName = "删除项目信息", description = "暂无", prerequisite = "暂无")
	public void deleteProject(@Valid Pm_project pm_project) {
		 pm_projectMapper.deleteProject(pm_project);
	}*/

}