/**
 * Copyrigt (2020, ) Institute of Software, Chinese Academy of Sciences
 */
package com.cn.services;

import org.springframework.beans.factory.annotation.Autowired;
import com.cn.mappers.Pm_storyMapper;
import com.cn.models.Pm_story;
import com.github.tools.annotations.api.FunctionDescriber;
import com.github.webfrk.core.HttpBodyHandler;
import com.github.tools.annotations.ServiceDefinition;
import javax.validation.*;
import javax.validation.constraints.*;

/**
 * This code is auto-generated by <code>ServiceGenerator<code>
 *
 */
@ServiceDefinition
public class Pm_storyService extends HttpBodyHandler {

	@Autowired
	private Pm_storyMapper pm_storyMapper;

	@FunctionDescriber(shortName = "添加用户故事", description = "暂无", prerequisite = "暂无")
	public void addPmStory(@Valid Pm_story pm_story) {
		 pm_storyMapper.addPmStory(pm_story);
	}

	@FunctionDescriber(shortName = "根据Id删除用户故事", description = "暂无", prerequisite = "暂无")
	public void deletePmStory(@Valid Pm_story pm_story) {
		 pm_storyMapper.deletePmStory(pm_story);
	}

	@FunctionDescriber(shortName = "根据id更新用户故事", description = "暂无", prerequisite = "暂无")
	public void updatePmStory(@Valid Pm_story pm_story) {
		 pm_storyMapper.updatePmStory(pm_story);
	}

	@FunctionDescriber(shortName = "根据泳道id和项目id查询用户故事", description = "暂无", prerequisite = "暂无")
	public Pm_story getLaneStory(Integer lane_id,Integer project_id) throws Exception {
		if(lane_id == null||project_id == null){
			throw new Exception("请求参数有问题");
		}
		return pm_storyMapper.getLaneStory(lane_id,project_id);
	}

	@FunctionDescriber(shortName = "根据id查询用户故事", description = "暂无", prerequisite = "暂无")
	public Pm_story getPmStory(Integer story_id)  throws Exception{
		if(story_id == null){
			throw new Exception("请求参数有问题");
		}
		return pm_storyMapper.getPmStory(story_id);
	}

}