/**
 * Copyrigt (2020, ) Institute of Software, Chinese Academy of Sciences
 */
package com.cn.services;

import org.springframework.beans.factory.annotation.Autowired;
import com.cn.mappers.Pm_taskMapper;
import com.cn.models.Pm_task;
import com.cn.models.Pm_version;
import com.github.tools.annotations.api.FunctionDescriber;
import com.github.webfrk.core.HttpBodyHandler;
import com.github.tools.annotations.ServiceDefinition;
import java.math.BigInteger;
import javax.validation.constraints.*;
import javax.validation.*;

/**
 * This code is auto-generated by <code>ServiceGenerator<code>
 *
 */
@ServiceDefinition
public class Pm_taskService extends HttpBodyHandler {

	@Autowired
	private Pm_taskMapper pm_taskMapper;

	@FunctionDescriber(shortName = "根据用户故事id展示该用户故事的任务", description = "暂无", prerequisite = "暂无")
	public java.util.List<com.cn.models.Pm_task> listPm_task(BigInteger story_id) {
		return pm_taskMapper.listPm_task(story_id);
	}
	
    //录入任务，
	@FunctionDescriber(shortName = "录入任务", description = "暂无", prerequisite = "暂无")
	public void addPm_task(@Valid Pm_task pm_task) {
		 pm_taskMapper.addPm_task(pm_task);
	}

	@FunctionDescriber(shortName = "根据任务id删除任务", description = "暂无", prerequisite = "暂无")
	public void deletePm_task(@Valid Pm_task pm_task) {
		 pm_taskMapper.deletePm_task(pm_task);
	}

}